### ISSUE TITLE
Amount dosent match sum of orderitems error

### ISSUE THREAD

**Issue by maxwhite** [DIBS-Payment-Services/Magento1_easy#12]
After this fix
https://github.com/DIBS-Payment-Services/Magento1_dibseasy/commit/6b10e9f185c78b818fb3a1be8a7342f922399000
we have this error:
2017-08-22T10:15:28+00:00 ERR (3): Dibs_EasyPayment_Api_Exception_Response: Amount dosent match sum of orderitems in /var/www/httpsdocs/mgnt/lib/Dibs/EasyPayment/Api/Client.php:111 Stack trace: #0 /var/www/httpsdocs/mgnt/lib/Dibs/EasyPayment/Api/Client.php(87): Dibs_EasyPayment_Api_Client->prepareResponse(Resource id #32) #1 /var/www/httpsdocs/mgnt/lib/Dibs/EasyPayment/Api/Service/Action/Payment/Create.php(63): Dibs_EasyPayment_Api_Client->request('https://test.ap...', 'POST', Array) #2 /var/www/httpsdocs/mgnt/lib/Dibs/EasyPayment/Api/Service/Payment.php(53): Dibs_EasyPayment_Api_Service_Action_Payment_Create->request(Array) #3 /var/www/httpsdocs/mgnt/app/code/community/Dibs/EasyCheckout/Model/Api.php(54): Dibs_EasyPayment_Api_Service_Payment->create(Array) #4 /var/www/httpsdocs/mgnt/app/code/community/Dibs/EasyCheckout/Model/Checkout.php(50): Dibs_EasyCheckout_Model_Api->createPayment(Object(Mage_Sales_Model_Quote)) #5 /var/www/httpsdocs/mgnt/app/code/community/Dibs/EasyCheckout/controllers/CheckoutController.php(49): Dibs_EasyCheckout_Model_Checkout->createPaymentId(Object(Mage_Sales_Model_Quote)) #6 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Dibs_EasyCheckout_CheckoutController->indexAction() #7 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index') #8 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http)) #9 /var/www/httpsdocs/mgnt/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch() #10 /var/www/httpsdocs/mgnt/app/Mage.php(683): Mage_Core_Model_App->run(Array) #11 /var/www/httpsdocs/mgnt/index.php(82): Mage::run('', 'store') #12 {main}
It means DIBS validate request amount total and calculated

**Comment by TheisCorfixenVaimo** [comment]
@maxwhite the exception mentioned here is the one that is removed in the latest version. Are you sure that the module have been updated. 

It could also be that you have opCache enabled on the server, this can be cleared by running the following php script:

`<?php opcache_reset(); `

Or restarting the PHP service in your server.

**Comment by EasyByNets** [comment]
@TheisCorfixenVaimo  We have had great success with our suppliers offering a testshop at their hosting solution, where you could push the changes.
This takes a lot of time for us, every time we need to update the module.
For example, my colleague is not at work today and therefore we can't test this.
Would this be a possibility as well?

**Comment by maxwhite** [comment]
The previous issue was that: 
2017-08-10T08:29:52+00:00 ERR (3): Dibs_EasyPayment_Api_Exception_Request: Order amount not equal with items total amount in lib/Dibs/EasyPayment/Api/Service/Action/Payment/Create.php:121
It means that validation fails and request will not be sent to the server
You've removed validation code but now we have another issue:
2017-08-22T09:43:35+00:00 ERR (3): Dibs_EasyPayment_Api_Exception_Response: Amount dosent match sum of orderitems in lib/Dibs/EasyPayment/Api/Client.php:111
It means that request was sended to server and DIBS server validation was failed.  
So the issue still exists but now it is on DIBS side

**Comment by giano574** [comment]
Issue still exists. When will it be fixed?

**Comment by maxwhite** [comment]
HI @giano574, could you please provide more details ? Or is it possible to test it somewhere on your environment ?

**Comment by priyanka795** [comment]
Hi,
I have the same issue. But still didn't get any solution. I installed the latest module and my Magento version is 1.9.2.4

Dibs_EasyPayment_Api_Exception_Response Object ( [message:protected] => Amount does not match sum of orderitems [string:Exception:private] => exception 'Dibs_EasyPayment_Api_Exception_Response' with message 'Amount does not match sum of orderitems' in /home/nybomvinewsisite/public_html/lib/Dibs/EasyPayment/Api/Client.php:110 Stack trace: #0 /home/nybomvinewsisite/public_html/lib/Dibs/EasyPayment/Api/Client.php(86): Dibs_EasyPayment_Api_Client->prepareResponse(Resource id #551)

Please update me soon.
Thanks

**Comment by TedSundin** [comment]
I have the same issue as well: 
2020-05-11T09:23:23+00:00 ERR (3): 
Dibs_EasyPayment_Api_Exception_Response: Amount does not match sum of orderitems in /home/nylogosol/public_html/store_dev_202005/lib/Dibs/EasyPayment/Api/Client.php:110

What can I do to fix this?

**Comment by mortenbirkelund** [comment]
We are experiencing the same thing, using the latest version as supplied by dibs.

**Comment by maxwhite** [comment]
> We are experiencing the same thing, using the latest version as supplied by dibs.

hi, could you please write to me on this email:
mbelo@nets.eu

**Comment by maxwhite** [comment]
> I have the same issue as well:
> 2020-05-11T09:23:23+00:00 ERR (3):
> Dibs_EasyPayment_Api_Exception_Response: Amount does not match sum of orderitems in /home/nylogosol/public_html/store_dev_202005/lib/Dibs/EasyPayment/Api/Client.php:110
> 
> What can I do to fix this?

HI, could you please write to me on email:
mbelo@nets.eu

**Comment by sebreens** [comment]
Also experiencing the same issue. Getting the following error returned from HTTPS request:
`Amount does not match sum of orderitems`
We are getting the error when there is a coupon code applied to our cart. Therefore it makes sense that the total price is not matching the sum of item prices.
Is it possible to somehow give Nets the discount amount? Or disable the validation?
